[package]
name = "capitol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
serde = { version = "1.0.217", features = ["derive"] }
ureq = { version = "2.12.1", features = ["json"] }
winnow = "0.6.22"
