[package]
name = "capitol"
version = "0.1.0"
edition = "2021"
description = "Parse citations of United States Congressional legislation"
repository = "https://github.com/blackerby/capitol"
license = "MIT"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
winnow = "0.6.22"
