[package]
name = "capitol"
version = "0.2.0"
edition = "2021"
description = "Parse United States Congress legislative document citations"
repository = "https://github.com/blackerby/capitol"
license = "MIT"
